/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Club = IDL.Record({
  'id' : IDL.Nat,
  'primaryColor' : IDL.Text,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'description' : IDL.Text,
  'logoUrl' : IDL.Text,
  'secondaryColor' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'clubId' : IDL.Int,
  'name' : IDL.Text,
  'priceInPence' : IDL.Nat,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'sizes' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'colors' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const StripeConfiguration = IDL.Record({
  'secretKey' : IDL.Text,
  'allowedCountries' : IDL.Vec(IDL.Text),
});
export const ShoppingItem = IDL.Record({
  'name' : IDL.Text,
  'amount' : IDL.Nat,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'itemsJson' : IDL.Text,
  'totalInPence' : IDL.Nat,
  'status' : IDL.Text,
  'stripeSessionId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClub' : IDL.Func([Club], [], []),
  'createProduct' : IDL.Func([Product], [], []),
  'deleteClub' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllClubs' : IDL.Func([], [IDL.Vec(Club)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClubBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Club)], ['query']),
  'getGeneralStock' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsByClub' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateClub' : IDL.Func([Club], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'verifyAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'createCheckoutSession' : IDL.Func([IDL.Vec(ShoppingItem), IDL.Text, IDL.Text], [IDL.Text], []),
  'createOrder' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrderByStripeSession' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Club = IDL.Record({
    'id' : IDL.Nat,
    'primaryColor' : IDL.Text,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'description' : IDL.Text,
    'logoUrl' : IDL.Text,
    'secondaryColor' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'clubId' : IDL.Int,
    'name' : IDL.Text,
    'priceInPence' : IDL.Nat,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'sizes' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'colors' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const StripeConfiguration = IDL.Record({
    'secretKey' : IDL.Text,
    'allowedCountries' : IDL.Vec(IDL.Text),
  });
  const ShoppingItem = IDL.Record({
    'name' : IDL.Text,
    'amount' : IDL.Nat,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'itemsJson' : IDL.Text,
    'totalInPence' : IDL.Nat,
    'status' : IDL.Text,
    'stripeSessionId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClub' : IDL.Func([Club], [], []),
    'createProduct' : IDL.Func([Product], [], []),
    'deleteClub' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllClubs' : IDL.Func([], [IDL.Vec(Club)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClubBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Club)], ['query']),
    'getGeneralStock' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsByClub' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateClub' : IDL.Func([Club], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'verifyAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'createCheckoutSession' : IDL.Func([IDL.Vec(ShoppingItem), IDL.Text, IDL.Text], [IDL.Text], []),
    'createOrder' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrderByStripeSession' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };